#!/usr/bin/env bash
set -o errexit -o nounset -o pipefail
# set -x

export TF_ENVIRONMENT_CONF="$1"

DIR="$(dirname "$BASH_SOURCE")"
source "${DIR}/common-functions.sh"

docker_tf init -lock=false
docker_tf fmt -write=false -check=true -diff=true
docker_tf validate
docker_tf plan -lock=false
